sudo: required
services:
    - docker
env:
    global:
        # get the git SHA so we can version the containers
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:

    # decrypt
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d


    #install google SDK (including kubectl)
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl

    # authenticate using info from the (now) decrypted service account credentials
    - gcloud auth activate-service-account --key-file service-account.json

    # specify the project
    - gcloud config set project multi-k8s-264620

    # specify the AZ in which to run
    - gcloud config set compute/zone us-east1-b

    # specify which cluster to issue commands to
    - gcloud container clusters get-credentials multi-cluster 

    # login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # build the dev/test image and run the test
    - docker build -t cuffycoder/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true cuffycoder/react-test npm run test 

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master



